wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    session_history: code/_session_history.ipynb
    start_time: 1658535592
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      4: 3.8.13
      5: 0.12.21
      8:
      - 1
      - 5
